/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.EAssociado;
import entidade.EItemPedido;
import entidade.EPedido;
import entidade.EProduto;
import java.awt.Dimension;
import java.text.NumberFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NAssociado;
import negocio.NPedido;
import negocio.NProduto;

/**
 *
 * @author Heuber
 */
public class PedidoCadastro extends javax.swing.JInternalFrame {

    JDesktopPane principal;
    EPedido pedido;

    /**
     * Creates new form VendaCadastro
     */
    public PedidoCadastro() {
        initComponents();
    }

    public PedidoCadastro(JDesktopPane instancia) {
        this();
        principal = instancia;
        pedido = new EPedido();

        limparTela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        cmdLimpar = new javax.swing.JButton();
        cmdSalvar = new javax.swing.JButton();
        cmdExcluir = new javax.swing.JButton();
        btnPesquisar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnPesquisar3 = new javax.swing.JButton();
        cmdFechar = new javax.swing.JButton();
        cmbAssociado = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Pedido");
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jLabel1.setText("Associado");
        jLabel1.setToolTipText("");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto");
        jLabel2.setToolTipText("");

        cmbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdutoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Quantidade");
        jLabel3.setToolTipText("");

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdicionar.setText("Adicionar ");
        btnAdicionar.setToolTipText("");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRetirar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor Unitario", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblItem);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Valor Total");
        jLabel4.setToolTipText("");

        txtValorTotal.setEditable(false);
        txtValorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cmdLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdLimpar.setText("Limpar");
        cmdLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimparActionPerformed(evt);
            }
        });

        cmdSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdSalvar.setText("Salvar");
        cmdSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalvarActionPerformed(evt);
            }
        });

        cmdExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdExcluir.setText("Excluir");
        cmdExcluir.setEnabled(false);

        btnPesquisar1.setText("Pesquisar");
        btnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar1ActionPerformed(evt);
            }
        });
        btnPesquisar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnPesquisar1PropertyChange(evt);
            }
        });

        jLabel6.setText("Identificador");
        jLabel6.setToolTipText("");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        btnPesquisar3.setText("Pesquisar");
        btnPesquisar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar3ActionPerformed(evt);
            }
        });

        cmdFechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdFechar.setText("Fechar");
        cmdFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFecharActionPerformed(evt);
            }
        });

        cmbAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAssociadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(237, 237, 237)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                            .addComponent(txtQuantidade))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisar3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cmbAssociado, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPesquisar1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPesquisar1)
                    .addComponent(jLabel1)
                    .addComponent(cmbAssociado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limparTela() {

        pedido = new EPedido();

        txtCodigo.setText("");
        txtQuantidade.setText("");

        cmdExcluir.setEnabled(false);

        //Carrega novamente ss combos
        carregarCombos();

        //Carrega a tabela de itens
        carregarTabela(pedido.getListaItens());

    }

    private void carregarCombos() {

        try {

            //Carregando produtos
            cmbProduto.removeAll();
            cmbProduto.addItem(new util.ComboItem("Selecione...", "0"));

            for (EProduto produto : new NProduto().listar(new EProduto())) {
                cmbProduto.addItem(new util.ComboItem(produto.getNome(),
                        String.valueOf(produto.getCodigo())));
            }

            //Carregando associados
            cmbAssociado.removeAll();
            cmbAssociado.addItem(new util.ComboItem("Selecione...", "0"));

            for (EAssociado associado : new NAssociado().listar("")) {
                cmbAssociado.addItem(new util.ComboItem(associado.getNome(),
                        String.valueOf(associado.getCodigo())));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.principal, e.getMessage());
        }

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2,
                (d.height - this.getSize().height) / 2);
    }

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed


    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {

            EItemPedido item = new EItemPedido();

            util.ComboItem itemSelecionado = (util.ComboItem) cmbProduto.getModel().getSelectedItem();

            if (itemSelecionado.getCodigo().equals("0")) {
                throw new Exception("É necessário selecionar um produto.");
            }

            int codigoProduto = Integer.parseInt(itemSelecionado.getCodigo());

            EProduto produto;
            produto = new NProduto().consultar(codigoProduto);
            item.setProduto(produto);

            if (txtQuantidade.getText() == null
                    || txtQuantidade.getText().trim().equals("")
                    || txtQuantidade.getText().equals("0")) {
                throw new Exception("É necessário informar a quantidade do "
                        + "produto.");
            }

            item.setQuantidade(Double.parseDouble(txtQuantidade.getText()));

            if (item.getQuantidade() <= 0) {
                throw new Exception("É necessário informar a quantidade do "
                        + "produto.");
            }

            adicionaItemNaLista(item);

            carregarTabela(pedido.getListaItens());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "É necessário informar uma quantidade válida.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed


    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        try {

            if (tblItem.getSelectedRow() == -1) {
                throw new Exception("É necessário selecionar um item na lista.");
            }

            if (pedido.getListaItens().isEmpty()) {
                throw new Exception("É necessário ter algum item na lista para ser removido.");
            }

            pedido.getListaItens().remove(tblItem.getSelectedRow());

            carregarTabela(pedido.getListaItens());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void cmdLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_cmdLimparActionPerformed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed

    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void cmdSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalvarActionPerformed
        try {

            util.ComboItem itemSelecionado = (util.ComboItem) cmbAssociado.getModel().getSelectedItem();

            if (itemSelecionado.getCodigo().equals("0")) {
                throw new Exception("É necessário selecionar um associado.");
            }

            int codigoAssociado = Integer.parseInt(itemSelecionado.getCodigo());

            EAssociado associado;
            associado = new NAssociado().consultar(codigoAssociado);
            pedido.setAssociado(associado);

            NPedido nPedido = new NPedido();
            nPedido.salvar(pedido);

            JOptionPane.showMessageDialog(null, "Pedido registrado com sucesso!");
            limparTela();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "É necessário informar uma quantidade válida.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cmdSalvarActionPerformed

    private void btnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar1ActionPerformed

    }//GEN-LAST:event_btnPesquisar1ActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void btnPesquisar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisar3ActionPerformed

    private void btnPesquisar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnPesquisar1PropertyChange

    }//GEN-LAST:event_btnPesquisar1PropertyChange

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange


    }//GEN-LAST:event_formPropertyChange

    private void cmbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdutoActionPerformed
        try {

            if (cmbProduto.getSelectedIndex() != 0) {
                txtQuantidade.setText("1");
                txtQuantidade.grabFocus();
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmbProdutoActionPerformed

    private void cmdFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFecharActionPerformed
        this.hide();
    }//GEN-LAST:event_cmdFecharActionPerformed

    private void cmbAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAssociadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAssociadoActionPerformed

    private void carregarTabela(List<EItemPedido> itens) {

        Vector<String> cabecalho = new Vector<String>();
        cabecalho.add("Código");
        cabecalho.add("Produto");
        cabecalho.add("Quantidade");
        cabecalho.add("Valor Unitário");
        cabecalho.add("Valor Total");

        Vector detalhe = new Vector();

        pedido.setValorTotal(0);
        try {
            for (EItemPedido item : itens) {

                Vector<String> linha = new Vector<String>();
                linha.add(item.getProduto().getCodigo() + "");
                linha.add(item.getProduto().getNome());
                linha.add(item.getQuantidade() + "");
                linha.add(NumberFormat.getCurrencyInstance().format(item.getProduto().getValor()));
                linha.add(NumberFormat.getCurrencyInstance().format(item.getQuantidade() * item.getProduto().getValor()));
                detalhe.add(linha);

                pedido.setValorTotalAcumulando(item.getQuantidade() * item.getProduto().getValor());
            }
            tblItem.setModel(new DefaultTableModel(detalhe, cabecalho));

            txtValorTotal.setText(NumberFormat.getCurrencyInstance().format(pedido.getValorTotal()));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisar1;
    private javax.swing.JButton btnPesquisar3;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JComboBox cmbAssociado;
    private javax.swing.JComboBox cmbProduto;
    private javax.swing.JButton cmdExcluir;
    private javax.swing.JButton cmdFechar;
    private javax.swing.JButton cmdLimpar;
    private javax.swing.JButton cmdSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables

    private void adicionaItemNaLista(EItemPedido item) {

        boolean achou = false;
        double qtde = 0;
        
        for (EItemPedido itemLista : pedido.getListaItens()) {

            if (itemLista.getProduto().getCodigo() == item.getProduto().getCodigo()) {
                achou = true;
                qtde = itemLista.getQuantidade();
                itemLista.setQuantidade(qtde + item.getQuantidade());
            }

        }
        if (!achou) {
            pedido.getListaItens().add(item);
        }

    }
}
